set nocompatible

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-speeddating'
Plug 'vim-scripts/utl.vim'
Plug 'itchyny/lightline.vim'
Plug 'godlygeek/tabular'
Plug 'ervandew/supertab'
Plug 'easymotion/vim-easymotion'
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
" Plug 'neovim/nvim-lspconfig'  " wait for nvim 0.5

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'majutsushi/tagbar', { 'on': 'TagbarOpenAutoClose' }

Plug 'xolox/vim-misc', { 'for': ['rust', 'haskell'] }
Plug 'xolox/vim-easytags', { 'for': ['rust', 'haskell'] }
Plug 'rust-lang/rust.vim', { 'for': 'rust' }
Plug 'tpope/vim-markdown', { 'for': 'markdown' }
Plug 'eagletmt/neco-ghc', { 'for': 'haskell' }
Plug 'jceb/vim-orgmode', { 'for': 'org' }
Plug 'zchee/deoplete-jedi', { 'for': 'python' }
Plug 'udalov/kotlin-vim', { 'for': 'kotlin' }
Plug 'JuliaEditorSupport/julia-vim'
call plug#end()




" Enable syntax highlighting
syntax on
filetype plugin indent on

color jellybeans

" Add line numbers
set number
set relativenumber
set ruler

" Set encoding
set encoding=utf-8

" Whitespace stuff
set nowrap
set linebreak
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Move always one display line
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

" Show trailing spaces and highlight hard tabs
set list listchars=tab:»·,trail:·

" Highlight current line
set cursorline

" Statusline
set noshowmode

" enable mouse support
set mouse=a

" faster scrolling
set lazyredraw

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Strip trailing whitespaces on each save
fun! <SID>StripTrailingWhitespaces()
    if exists('b:noStripWhitespace')
        return
    endif

    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" set language for the spell checks to English
:set spelllang=en_us

" Search related settings
set ignorecase
set smartcase
set incsearch
set hlsearch

" Map Leader
let mapleader = ' '
let maplocalleader = '-'

" Map Ctrl+l to clear highlighted searches
nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>

" Map Ctrl-s to save
inoremap <C-s> <C-g>u<ESC>:w<CR>a
noremap <C-s> :w<CR>

" close all with :Q
command Q :qa

" delete without overwriting the register
noremap s "_d

" enable @<register> in visual mode
xnoremap @ :<C-u>call ExecuteMacroOverVisualRange()<CR>
function! ExecuteMacroOverVisualRange()
  echo "@".getcmdline()
  execute ":'<,'>normal @".nr2char(getchar())
endfunction

" Easier window navigation
if has('nvim')
    tnoremap <A-a> <C-\><C-n>

    tnoremap <A-h> <C-\><C-n><C-w>h
    tnoremap <A-j> <C-\><C-n><C-w>j
    tnoremap <A-k> <C-\><C-n><C-w>k
    tnoremap <A-l> <C-\><C-n><C-w>l

    tnoremap <A-Left>  <C-\><C-n><C-w>h
    tnoremap <A-Down>  <C-\><C-n><C-w>j
    tnoremap <A-Up>    <C-\><C-n><C-w>k
    tnoremap <A-Right> <C-\><C-n><C-w>l
endif
noremap <A-h> <C-w>h
noremap <A-j> <C-w>j
noremap <A-k> <C-w>k
noremap <A-l> <C-w>l
noremap <A-Left> <C-\><C-n><C-w>h
noremap <A-Down> <C-\><C-n><C-w>j
noremap <A-Up> <C-\><C-n><C-w>k
noremap <A-Right> <C-\><C-n><C-w>l

" Map Ctrl-q to run macro
nnoremap <C-q> @q

" Map Leader+e go from terminal to normal mode (only nvim)
if has('nvim')
    tnoremap <LocalLeader><ESC> <C-\><C-n>
endif

" Highlight the 100 chars margin
if exists('+colorcolumn')
    set colorcolumn=100
endif
if has('nvim')
    set inccommand=nosplit
endif

" Disable code folding
set nofoldenable

" Directories for swp files
set backupdir=~/.vimbackup
set directory=~/.vimbackup

" Ignore these filetypes when expanding a wildcard
set wildignore=*.class,*.jar,*.tar*,*.pdf,*.png,*.jpg,*.jpeg,*.tiff,*.tif

" Simplify clipboard usage
noremap <Leader>P "+P
noremap <Leader>p "+p
noremap <LocalLeader>P :put =system('tmux show-buffer')
noremap <LocalLeader>p "+p
noremap <silent> <Leader>y "+y <bar> :call system("tmux set-buffer", getreg("@+"))<CR>

" EasyMotion configuration
let g:EasyMotion_do_mapping = 1
let g:EasyMotion_smartcase = 1
nmap s <Plug>(easymotion-s2)

" Tabular configuration
nmap <Leader>a :Tabularize /
vmap <Leader>a :Tabularize /

" deoplete configuration
let g:deoplete#enable_at_startup = 1
set completeopt-=preview

" Lightline configuration
set laststatus=2

" SuperTab configuration
let g:SuperTabCrMapping = 1
let g:SuperTabMappingForward = '<s-tab>'
let g:SuperTabMappingBackward = '<tab>'

" neosnippet configuration
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
smap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" NERDTree configuration
let NERDTreeIgnore=['\.pyc$', '\.rbc$', '\~$']
map <Leader>n :NERDTreeToggle<CR>

" EasyTags configuration
let g:easytags_async = 1
let g:easytags_events = ['BufWritePost']
let g:easytags_include_members = 1
let g:easytags_auto_highlight = 0

" tagbar settings
nnoremap <silent> <F9> :TagbarOpenAutoClose<CR>
let g:tagbar_type_haskell = {
    \ 'ctagsbin'  : 'hasktags',
    \ 'ctagsargs' : '-x -c -o-',
    \ 'kinds'     : [
        \  'm:modules:0:1',
        \  'd:data: 0:1',
        \  'd_gadt: data gadt:0:1',
        \  't:type names:0:1',
        \  'nt:new types:0:1',
        \  'c:classes:0:1',
        \  'cons:constructors:1:1',
        \  'c_gadt:constructor gadt:1:1',
        \  'c_a:constructor accessors:1:1',
        \  'ft:function types:1:1',
        \  'fi:function implementations:0:1',
        \  'o:others:0:1'
    \ ],
    \ 'sro'        : '.',
    \ 'kind2scope' : {
        \ 'm' : 'module',
        \ 'c' : 'class',
        \ 'd' : 'data',
        \ 't' : 'type'
    \ },
    \ 'scope2kind' : {
        \ 'module' : 'm',
        \ 'class'  : 'c',
        \ 'data'   : 'd',
        \ 'type'   : 't'
    \ }
\ }
let g:tagbar_type_rust = {
    \ 'ctagstype' : 'rust',
    \ 'kinds' : [
        \'T:types',
        \'f:functions',
        \'g:enums',
        \'s:structs',
        \'m:modules',
        \'c:consts',
        \'t:traits',
        \'i:impls',
    \ ],
    \}

" make uses real tabs
au FileType make set noexpandtab

" wrap lines
au FileType text,tex,latex,plaintex,markdown set wrap | set spell

" add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript

" spell check all git commit messages
au BufNewFile,BufRead COMMIT_EDITMSG set spell

" don't strip whitespaces for 'git add --patch '
au BufNewFile,BufRead ADD_EDIT.patch let b:noStripWhitespace=1

" set wrap for the quickfix list
au FileType qf setlocal wrap

" setup org-mode
au FileType org set textwidth=0 | set shiftwidth=2 | set tabstop=2 | set softtabstop=2 | set nowrap

" disable spell in terminal
if has('nvim')
    au TermOpen * setlocal nospell
endif
