# This script is always sourced
#

# Setup path
export PATH="$PATH:$HOME/.local/bin/:$HOME/.cargo/bin"


# Setup variables
if type nvim &> /dev/null; then
    export EDITOR=nvim
else
    export EDITOR=vim
fi
export PAGER=less
export JAVA_HOME=/usr/lib/jvm/default-java/
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
export R_LIBS_USER=~/.R/library
