#!/usr/bin/env python3

import h5py
import medpy.io
import argparse
import numpy as np
from pathlib import Path


def main(hdf_file, hdf_dataset, mha_file, compression):
    with h5py.File(hdf_file, 'r') as hdf:
        img = hdf[hdf_dataset][:].astype(np.int32)
        assert img.ndim == 3, 'Only 3d images are supported'

        medpy.io.save(img, mha_file, force=True, use_compression=compression)




if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Converts 3d HDF5 datasets to MHA files.')
    parser.add_argument('--no_compression', action='store_true', help='disable compression for the output file')
    parser.add_argument('hdf_file', type=Path, help='input HDF5 file')
    parser.add_argument('hdf_dataset', type=str, help='input HDF5 dataset')
    parser.add_argument('mha_file', type=str, help='output MHA file')

    _args = parser.parse_args()
    main(_args.hdf_file, _args.hdf_dataset, _args.mha_file, not _args.no_compression)

